name: mobilepad
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  # crypt: ^4.0.1
  path: ^1.8.0
  postgres: ^2.3.2
  shelf: ^1.1.4
  shelf_router: ^1.0.0
  shelf_router_generator: ^1.0.0
  dotenv: ^3.0.0
  jose: ^0.3.2
  jwt_decoder: ^2.0.1
  crypto: ^3.0.1
  encrypt: ^5.0.0

dev_dependencies:
  build_runner: ^2.0.4
  pedantic: ^1.10.0
